# Generated by Django 5.2.17 on 2026-10-01 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentrecord',
            name='reason',
            field=models.CharField(blank=True, max_length=200, verbose_name='Motivo / tipo de consulta'),
        ),
        migrations.AddField(
            model_name='treatmentrecord',
            name='treatment',
            field=models.TextField(blank=True, verbose_name='Tratamiento / indicaciones'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='treatmentrecord',
            name='description',
            field=models.TextField(verbose_name='Observaciones'),
        ),
    ]
