# Generated by Django 5.2.17 on 2026-09-23 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "specialty",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Especialidad"
                    ),
                ),
                (
                    "appointment_duration_minutes",
                    models.PositiveIntegerField(
                        default=30, verbose_name="Duración de cada turno (minutos)"
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Activo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["user__first_name", "user__last_name"],
            },
        ),
    ]
