# Generated by Django 5.2.17 on 2026-09-23 20:17

import django.contrib.postgres.fields.ranges
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_datetime", models.DateTimeField()),
                ("end_datetime", models.DateTimeField()),
                (
                    "period",
                    django.contrib.postgres.fields.ranges.DateTimeRangeField(
                        editable=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CONFIRMADA", "Confirmada"),
                            ("ATENDIDA", "Atendida"),
                            ("CANCELADA", "Cancelada"),
                            ("NO_ASISTIO", "No asistió"),
                        ],
                        default="CONFIRMADA",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notas")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["start_datetime"],
            },
        ),
    ]
