# Generated by Django 5.2.17 on 2026-09-26 01:48

import django.contrib.postgres.constraints
import django.db.models.deletion
from django.contrib.postgres.operations import BtreeGistExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_initial'),
        ('doctors', '0002_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        # Necesaria para que el ExclusionConstraint de más abajo pueda
        # usar un índice GiST sobre `doctor` (bigint) + `period` (rango
        # de fechas): sin esta extensión, PostgreSQL no tiene una clase
        # de operadores por omisión para comparar bigint con GiST.
        BtreeGistExtension(),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patients.patient'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.CheckConstraint(condition=models.Q(('end_datetime__gt', models.F('start_datetime'))), name='appointment_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('status__in', ['CONFIRMADA', 'ATENDIDA'])), expressions=[('doctor', '='), ('period', '&&')], name='no_overlapping_active_appointments_per_doctor'),
        ),
    ]
