# Generated by Django 5.2.17 on 2026-09-23 20:17

import django.contrib.postgres.constraints
import django.contrib.postgres.operations
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("appointments", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Necesaria para que PostgreSQL permita comparar por igualdad
        # (el campo 'doctor') dentro de un ExclusionConstraint que
        # también usa '&&' (solapamiento) sobre un rango de fechas.
        # Sin esta extensión, la restricción anti-doble-reserva de más
        # abajo no se puede crear.
        django.contrib.postgres.operations.BtreeGistExtension(),
        migrations.AddField(
            model_name="appointment",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments_as_patient",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="appointment",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_datetime__gt", models.F("start_datetime"))),
                name="appointment_end_after_start",
            ),
        ),
        migrations.AddConstraint(
            model_name="appointment",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                condition=models.Q(("status__in", ["CONFIRMADA", "ATENDIDA"])),
                expressions=[("doctor", "="), ("period", "&&")],
                name="no_overlapping_active_appointments_per_doctor",
            ),
        ),
    ]
