# Generated by Django 5.2.17 on 2026-09-23 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("doctors", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AvailabilityException",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_datetime", models.DateTimeField(verbose_name="Desde")),
                ("end_datetime", models.DateTimeField(verbose_name="Hasta")),
                (
                    "type",
                    models.CharField(
                        choices=[("BLOQUEO", "Bloqueo / ausencia")],
                        default="BLOQUEO",
                        max_length=20,
                    ),
                ),
                (
                    "reason",
                    models.CharField(blank=True, max_length=255, verbose_name="Motivo"),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availability_exceptions",
                        to="doctors.doctor",
                    ),
                ),
            ],
            options={
                "ordering": ["start_datetime"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("end_datetime__gt", models.F("start_datetime"))
                        ),
                        name="availability_exception_end_after_start",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="WeeklySchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weekday",
                    models.IntegerField(
                        choices=[
                            (0, "Lunes"),
                            (1, "Martes"),
                            (2, "Miércoles"),
                            (3, "Jueves"),
                            (4, "Viernes"),
                            (5, "Sábado"),
                            (6, "Domingo"),
                        ],
                        verbose_name="Día de la semana",
                    ),
                ),
                ("start_time", models.TimeField(verbose_name="Hora de inicio")),
                ("end_time", models.TimeField(verbose_name="Hora de fin")),
                ("active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weekly_schedules",
                        to="doctors.doctor",
                    ),
                ),
            ],
            options={
                "ordering": ["weekday", "start_time"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("end_time__gt", models.F("start_time"))),
                        name="weekly_schedule_end_after_start",
                    )
                ],
            },
        ),
    ]
